[package]
name = "data-plane-api"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
tonic = "0.11.0"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.12.6"
tonic-build = "0.11.0"
