[package]
name = "proto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generated protobuf types for Envoy xDS APIs"

[dependencies]
prost = "0.13.3"
tonic = "0.12.3"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.13.3"
tonic-build = "0.12.3"
